apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: eks-cluster-composition
  annotations:
    guide: quickstart
    provider: aws
    vpc: default
spec:
  crossplane:
    version: ">=v1.2.0-0"
  dependsOn:
    - provider: crossplane/provider-aws
      version: "v0.18.2"
