---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-aws-eks 
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io   
spec:
  project: node-todo
  source:
    repoURL: https://github.com/akshay-cognologix/gitops-using-crossplane-argocd.git
    targetRevision: HEAD
    path: node-todo-app/
  destination:
    server: https://29948602D56563A4EEC87A11B7E011BE.gr7.us-east-2.eks.amazonaws.com
    namespace: node-todo
  syncPolicy:
    automated:
      prune: true    
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m  
